name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use GitHub-hosted runner

    steps:
      # Step 1: Pull the Docker image
      - name: Pull Docker image
        run: sudo docker pull abhi96k/cicd-pipeline:latest

      # Step 2: Delete the old Docker container (if exists)
      - name: Delete old Docker container
        run: sudo docker rm -f cicd-pipeline-container || true

      # Step 3: Run the new Docker container
      run: sudo docker run -d -p 8888:8080 --name cicd-pipeline-container abhi96k/cicd-pipeline:latest
